name: 'Google Cloud IaC'

defaults:
  run:
    working-directory: iac

on: 
  push:
    paths:
      - 'iac/**'

jobs:
  terraform:
    name: 'Terraform'
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup GCP Service Account
        uses: google-github-actions/setup-gcloud@v0
        with:
          service_account_email: ${{ secrets.GCP_SA_EMAIL }}
          service_account_key: ${{ secrets.GCP_SA_KEY }}

      - name: Terraform Setup
        uses: hashicorp/setup-terraform@v1
        with: 
          terraform-version: 1.1.7
      
      - name: Terraform Init
        run: terraform init

      - name: Terraform Format
        run: terraform fmt -check
      
      - name: Terraform Plan
        run: terraform plan
      
      - name: Terraform Apply
        if: github.ref == 'refs/head/main'
        run: terraform apply -auto-approve




