name: 'Create Visualization Resources'

defaults:
  run:
    shell: bash
    working-directory: visualization

on:
  workflow_dispatch:
  push:
    paths:
      - 'visualization/**'
      - '!visualization/README.md'
      - '!visualization/README.md'
      - '.github/workflows/visualization.yaml'


jobs:
  create:
    name: 'Vis'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Auth GCP Service Account
        uses: google-github-actions/auth@v0
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}
          cleanup_credentials: false

      - name: Python-Setup
        uses: actions/setup-python@v3
        with:
          python-version: '3.9'
          cache: 'pip'

      - name: Install Depedencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install -U spacy --quiet
          python -m spacy download en_core_web_sm --quiet
          python -m nltk.downloader stopwords

      - name: Build Visualization Artifacts
        run: |
          mkdir -p artifacts
          python main.py github-actions

      - name: Create Interactive HTML
        run:  jupyter nbconvert --execute --to html  dashboard.ipynb --no-input

      - name: Commit changed files and Push to main
        run: |
          git config --local user.name "IremErturk"
          git config --global user.email 'IremErturk@users.noreply.github.com'
          git add ./artifacts
          git add dashboard.html
          git commit -m "[automated] updating visualization assets"
          git push
